services:
  app:
    env_file:
      - .env.local
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
